v = input('Digite uma variavel qualquer: ')
print('O tipo dessa variavel é: ', type(v))
print('A variável tem somente espaços? ', v.isspace())
print('A variável é numérica? ', v.isnumeric())
print('A variavel é alfabética? ', v.isalpha())
print('A variavel é alfanúmerica? ', v.isalnum())
print('A variavel está em CAPS? ', v.isupper())
print('A variavel está em minusculas? ', v.islower())
print(('A variavel está captalizada? ', v.istitle()))